### PR TITLE
Replace Show Unreached Perks MCM toggle with a dropdown

### LINKED ISSUE #69: Add an MCM setting to hide only Training Center perks
Currently, "Show unreached ranks" is a single on/off setting, but we could replace it with a drop-down list for better customizability.

### PR DESCRIPTION
**Pull request by Iridar**
Fixes #69

Giggity

Previously, there was an MCM setting where the CPS would either hide all perks from unreached ranks or displayed all of them.

This PR replaces the toggle setting with a dropdown list, where the third option can be selected, which hides only perks that require Training Center from unreached ranks.

### CODE REVIEW

**Review by robojumper — COMMENTED** [review]
Seems fine to me but I have to admit I'm not even familiar with this version of the MCM macros.

**Comment by Iridar** [comment]
> Seems fine to me but I have to admit I'm not even familiar with this version of the MCM macros.

Ah yeah that's the MrNice's version I've been using. It's a huge timesaver, and includes a static macro for grabbing MCM settings values. Very QoL.

**Comment by Iridar** [comment]
There was an accidental edit to an unrelated line in one of the files, I removed it.

**Comment by Iridar** [comment]
Updated the code slightly so that two different places in code have a consistent view on what is a training center perk.

**Pull request merged**
